#!/bin/bash
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_MISSENSE_SNPEFF.freqUpper0.001.SkatO.assoc         ALL_MISSENSE_SNPEFF
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_MISSENSE_SNPEFF.freqUpper0.01.SkatO.assoc         ALL_MISSENSE_SNPEFF
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_LOF_HC_LOFTEE.freqUpper0.001.SkatO.assoc         ALL_LOF_HC_LOFTEE
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_LOF_HC_LOFTEE.freqUpper0.01.SkatO.assoc         ALL_LOF_HC_LOFTEE
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_MODERATE_HIGH_IMPACT_SNPEFF.freqUpper0.001.SkatO.assoc         ALL_MODERATE_HIGH_IMPACT_SNPEFF
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_MODERATE_HIGH_IMPACT_SNPEFF.freqUpper0.01.SkatO.assoc         ALL_MODERATE_HIGH_IMPACT_SNPEFF
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_LOF_HC_LOFTEE_and_CADD_20_VEP.freqUpper0.001.SkatO.assoc         ALL_LOF_HC_LOFTEE_and_CADD_20_VEP
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_LOF_HC_LOFTEE_and_CADD_20_VEP.freqUpper0.01.SkatO.assoc         ALL_LOF_HC_LOFTEE_and_CADD_20_VEP
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_MISSENSE_SNPEFF.freqUpper0.001.CMCWald.assoc         ALL_MISSENSE_SNPEFF
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_MISSENSE_SNPEFF.freqUpper0.01.CMCWald.assoc         ALL_MISSENSE_SNPEFF
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_LOF_HC_LOFTEE.freqUpper0.001.CMCWald.assoc         ALL_LOF_HC_LOFTEE
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_LOF_HC_LOFTEE.freqUpper0.01.CMCWald.assoc         ALL_LOF_HC_LOFTEE
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_MODERATE_HIGH_IMPACT_SNPEFF.freqUpper0.001.CMCWald.assoc         ALL_MODERATE_HIGH_IMPACT_SNPEFF
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_MODERATE_HIGH_IMPACT_SNPEFF.freqUpper0.01.CMCWald.assoc         ALL_MODERATE_HIGH_IMPACT_SNPEFF
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_LOF_HC_LOFTEE_and_CADD_20_VEP.freqUpper0.001.CMCWald.assoc         ALL_LOF_HC_LOFTEE_and_CADD_20_VEP
Rscript --vanilla ./../../manhattan_percohort_1e-6-gne.R         /data/CARD/PD/AMP_NIH/no_relateds/meta_risk_analysis/geneburden_risk_wGenentech/GENENTECH/gne.ALL_LOF_HC_LOFTEE_and_CADD_20_VEP.freqUpper0.01.CMCWald.assoc         ALL_LOF_HC_LOFTEE_and_CADD_20_VEP
